export const JASONSOFT_SEQ_LOGGER = 'JASONSOFT_SEQ_LOGGER';

export const JASONSOFT_SEQ_LOGGER_OPTIONS = 'JASONSOFT_SEQ_LOGGER_OPTIONS';

export const NETWORK_ERRORS = [
  'ENETUNREACH',
  'ECONNABORTED',
  'ECONNREFUSED',
  'ECONNRESET',
  'ENOTFOUND',
  'ESOCKETTIMEDOUT',
  'ETIMEDOUT',
  'EHOSTUNREACH',
  'EPIPE',
  'EAI_AGAIN',
  'EBUSY',
];
